version: '3'

services:
  backend:
    build: 
      context: backend
    ports:
      - "5000:5000"

  nginx:
    image: nginx:latest
    volumes:
      - ./backend/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    ports:
      - "80:80"
 
  # frontend:
  #   build:
  #     context: frontend
  #   depends_on:
  #     - backend
  #   ports:
  #     - "8080:8080"